server:
  port: ${PORT:9000}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${ALLOWED_ORIGIN:http://localhost:5173}
            allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: backend
          uri: ${BACKEND_URL:http://localhost:8080}
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**
        - id: portfolio-service
          uri: ${PORTFOLIO_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/portfolio/**
        - id: portfolios-service
          uri: ${PORTFOLIO_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/portfolios/**
        - id: market-data
          uri: ${PORTFOLIO_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/market/**
        - id: profile-service
          uri: ${PORTFOLIO_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/profile/**
        - id: leaderboard-service
          uri: ${PORTFOLIO_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/leaderboard/**
