package com.springhi.user.service;

import com.springhi.user.model.User;
import com.springhi.user.model.UserSubscription;
import com.springhi.user.repository.PaymentHistoryRepository;
import com.springhi.user.repository.PaymentMethodRepository;
import com.springhi.user.repository.UserRepository;
import com.springhi.user.repository.UserSubscriptionRepository;
import com.stripe.exception.StripeException;
import com.stripe.model.Customer;
import com.stripe.model.Event;
import com.stripe.model.EventCollection;
import com.stripe.model.Invoice;
import com.stripe.model.StripeObject;
import com.stripe.model.Subscription;
import com.stripe.model.testhelpers.TestClock;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.time.Duration;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Stripe sandbox integration tests that exercise the real Stripe API (test mode) end to end:
 * test clocks, customers, sandbox test cards, subscription create/update/cancel, and the webhook
 * projector that mirrors events into the local tables. Events generated by Stripe (e.g. on clock
 * advance) are polled via {@code Event.list} and replayed through {@link StripeWebhookService}, so
 * no public webhook endpoint / ngrok is required.
 *
 * <p>Gated behind the {@code stripe.it=true} system property so the normal {@code mvn test} run
 * (the 15 deterministic Mockito tests) is unaffected. Run with:
 * <pre>
 *   mvn -q -DskipTests=false -Dstripe.it=true -Dtest=StripeSandboxIT test
 * </pre>
 * Requires {@code app.stripe.enabled=true} with sandbox {@code sk_test_...} keys and real
 * {@code price_...} ids configured in {@code application-local.yaml}, plus the local PostgreSQL DB.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@EnabledIfSystemProperty(named = "stripe.it", matches = "true")
class StripeSandboxIT {

    private static final Logger log = LoggerFactory.getLogger(StripeSandboxIT.class);
    private static final String SUCCESS_TOKEN = "tok_visa";
    private static final Set<String> INVOICE_PAID_TYPES = Set.of("invoice.paid", "invoice.payment_succeeded");

    @Autowired private StripeService stripeService;
    @Autowired private StripeWebhookService stripeWebhookService;
    @Autowired private SubscriptionService subscriptionService;
    @Autowired private UserSubscriptionRepository subscriptionRepository;
    @Autowired private PaymentHistoryRepository paymentHistoryRepository;
    @Autowired private PaymentMethodRepository paymentMethodRepository;
    @Autowired private UserRepository userRepository;

    private Long userId;

    // Per-test Stripe resources to tear down.
    private String createdClockId;
    private String createdCustomerId;
    private String createdSubscriptionId;
    private long testStartEpoch;

    @BeforeAll
    void createTestUser() {
        long suffix = System.currentTimeMillis();
        User u = new User();
        u.setUsername("stripe_it_" + suffix);
        u.setEmail("stripe_it_" + suffix + "@example.test");
        u.setPassword("stripe-it-password");
        u.setFirstName("Stripe");
        u.setLastName("IT");
        userId = userRepository.save(u).getId();
        log.info("IT: created test user id={} username={}", userId, u.getUsername());
    }

    @AfterAll
    void deleteTestUser() {
        if (userId == null) return;
        try {
            userRepository.deleteById(userId);
            log.info("IT: deleted test user id={}", userId);
        } catch (Exception e) {
            log.warn("IT: could not delete test user id={} (left as cruft): {}", userId, e.getMessage());
        }
    }

    @BeforeEach
    void resetState() {
        Assumptions.assumeTrue(stripeService.isEnabled(),
                "Stripe not enabled — configure app.stripe.enabled=true with a sandbox key");
        testStartEpoch = System.currentTimeMillis() / 1000L;
        createdClockId = null;
        createdCustomerId = null;
        createdSubscriptionId = null;
        paymentHistoryRepository.findByUserIdOrderByPaymentDateDesc(userId)
                .forEach(paymentHistoryRepository::delete);
        paymentMethodRepository.findByUserIdOrderByCreatedAtDesc(userId)
                .forEach(paymentMethodRepository::delete);
        subscriptionRepository.findByUserId(userId).ifPresent(sub -> {
            sub.setPlanName("FREE");
            sub.setStatus("ACTIVE");
            sub.setBillingCycle(null);
            sub.setEndDate(null);
            sub.setNextBillingDate(null);
            sub.setPendingPlanName(null);
            sub.setPendingBillingCycle(null);
            sub.setStripeCustomerId(null);
            sub.setStripeSubscriptionId(null);
            sub.setStripeTestClockId(null);
            subscriptionRepository.save(sub);
        });
    }

    @AfterEach
    void cleanupStripe() {
        if (createdSubscriptionId != null) {
            try {
                Subscription retrieved = Subscription.retrieve(createdSubscriptionId);
                if ("canceled".equalsIgnoreCase(retrieved.getStatus())) {
                    // already canceled
                } else {
                    retrieved.cancel();
                }
                log.info("IT cleanup: canceled Stripe subscription {}", createdSubscriptionId);
            } catch (Exception e) {
                log.warn("IT cleanup: could not cancel subscription {}: {}", createdSubscriptionId, e.getMessage());
            }
        }
        if (createdCustomerId != null) {
            try {
                Customer.retrieve(createdCustomerId).delete();
                log.info("IT cleanup: deleted Stripe customer {}", createdCustomerId);
            } catch (Exception e) {
                log.warn("IT cleanup: could not delete customer {}: {}", createdCustomerId, e.getMessage());
            }
        }
        if (createdClockId != null) {
            try {
                TestClock.retrieve(createdClockId).delete();
                log.info("IT cleanup: deleted Stripe test clock {}", createdClockId);
            } catch (Exception e) {
                log.warn("IT cleanup: could not delete test clock {}: {}", createdClockId, e.getMessage());
            }
        }
    }

    // ===================== Scenarios =====================

    /** New BASIC-monthly subscription on a test clock, then a renewal fired by advancing the clock. */
    @Test
    void subscribeAndRenew_successCard() throws Exception {
        ClockSub cs = setupClockSubscription("BASIC", "MONTHLY", SUCCESS_TOKEN);
        log.info("IT[renew]: subscribed stripeSub={} customer={} clock={}",
                cs.subscription.getId(), createdCustomerId, createdClockId);

        // First invoice.paid fires at the clock's frozen time (subscription_create).
        Event first = waitForEvent(INVOICE_PAID_TYPES, createdCustomerId, null, null);
        assertNotNull(first, "first invoice.paid event not received from Stripe");
        log.info("IT[renew]: replaying first invoice.paid event id={}", first.getId());
        Invoice firstInvoice = (Invoice) first.getDataObjectDeserializer().deserializeUnsafe();
        log.info("IT[renew]: first invoice id={} periodStart={} periodEnd={}",
                firstInvoice.getId(), firstInvoice.getPeriodStart(), firstInvoice.getPeriodEnd());
        stripeWebhookService.handleEvent(first);

        UserSubscription afterFirst = subscriptionRepository.findByUserId(userId).orElseThrow();
        assertNotNull(afterFirst.getNextBillingDate(), "nextBillingDate should be set after first invoice.paid");
        assertEquals("BASIC", afterFirst.getPlanName());
        assertEquals("MONTHLY", afterFirst.getBillingCycle());
        // Race-safe: a live backend (or this replay) may have already recorded this invoice.paid;
        // onInvoicePaid is idempotent by stripe_invoice_id, so assert the row exists by invoice id.
        assertTrue(paymentHistoryRepository.existsByStripeInvoiceId(firstInvoice.getId()),
                "first invoice.paid should be recorded (by stripe invoice id)");
        log.info("IT[renew]: after first replay nextBillingDate={} firstInvoiceId={}",
                afterFirst.getNextBillingDate(), firstInvoice.getId());

        // Advance the clock to just past the current period end so the monthly renewal invoice fires.
        // (A fixed +30d can land one day short of a calendar-month boundary and miss the renewal.)
        stripeService.advanceTestClock(createdClockId, renewalAdvanceTarget(cs));
        // Wait for the RENEWAL invoice, excluding the first invoice by id: Stripe emits both
        // invoice.paid and invoice.payment_succeeded for one invoice, so excluding only the first
        // event id would prematurely match the first invoice's sibling event instead of the renewal.
        Event renewal = waitForEvent(INVOICE_PAID_TYPES, createdCustomerId, first.getId(), firstInvoice.getId());
        assertNotNull(renewal, "renewal invoice.paid event not received after clock advance");
        Invoice renewalInvoice = (Invoice) renewal.getDataObjectDeserializer().deserializeUnsafe();
        log.info("IT[renew]: renewal invoice id={} periodStart={} periodEnd={}",
                renewalInvoice.getId(), renewalInvoice.getPeriodStart(), renewalInvoice.getPeriodEnd());
        stripeWebhookService.handleEvent(renewal);

        UserSubscription afterRenewal = subscriptionRepository.findByUserId(userId).orElseThrow();
        // Race-safe by invoice id (see first-invoice note above).
        assertTrue(paymentHistoryRepository.existsByStripeInvoiceId(renewalInvoice.getId()),
                "renewal invoice.paid should be recorded (by stripe invoice id)");
        // Each nextBillingDate should sit ~1 cycle after its own invoice's periodStart. This verifies
        // the degenerate-create fix (first invoice periodEnd==periodStart -> nextBilling = periodStart
        // + 1 cycle) and stays robust in both test-clock and production renewal semantics, instead of
        // the brittle afterFirst->afterRenewal delta (which collapses to 0 in test-clock once the fix
        // lands, because the test-clock renewal invoice reports periodStart = t0, not the renewal time).
        long firstCycleDays = Duration.between(ldtFromEpoch(firstInvoice.getPeriodStart()), afterFirst.getNextBillingDate()).toDays();
        assertTrue(firstCycleDays >= 29 && firstCycleDays <= 31,
                "first nextBillingDate should be ~30 days after the create invoice periodStart, was " + firstCycleDays);
        long renewCycleDays = Duration.between(ldtFromEpoch(renewalInvoice.getPeriodStart()), afterRenewal.getNextBillingDate()).toDays();
        assertTrue(renewCycleDays >= 29 && renewCycleDays <= 31,
                "renewal nextBillingDate should be ~30 days after the renewal invoice periodStart, was " + renewCycleDays);
        log.info("IT[renew]: after renewal replay firstNextBilling={} ({}d from create), renewNextBilling={} ({}d from renewal)",
                afterFirst.getNextBillingDate(), firstCycleDays, afterRenewal.getNextBillingDate(), renewCycleDays);
    }

    /**
     * A subscription renewal with no usable payment method drives invoice.payment_failed, which
     * marks the local subscription PAST_DUE. Legacy test tokens like tok_chargeDeclined decline
     * even on attach, so the success card is attached (first invoice pays), then detached before the
     * renewal so the renewal charge has no payment method and fails.
     */
    @Test
    void paymentFailure_marksPastDue() throws Exception {
        ClockSub cs = setupClockSubscription("BASIC", "MONTHLY", SUCCESS_TOKEN);
        log.info("IT[fail]: subscribed stripeSub={} customer={}", cs.subscription.getId(), createdCustomerId);

        // Detach the default payment method so the renewal invoice cannot be paid.
        com.springhi.user.model.PaymentMethod localPm =
                paymentMethodRepository.findFirstByUserIdAndIsDefaultTrue(userId).orElse(null);
        assertNotNull(localPm, "default payment method should exist after subscribe");
        String stored = localPm.getCardNumberEncrypted();
        String stripePmId = stored != null && stored.startsWith("stripe:") ? stored.substring("stripe:".length()) : null;
        assertNotNull(stripePmId, "local payment method should reference a Stripe pm id");
        com.stripe.model.PaymentMethod.retrieve(stripePmId).detach();
        log.info("IT[fail]: detached Stripe payment method {} for userId={}", stripePmId, userId);

        // Advance the clock to just past the current period end so the renewal invoice fires, which
        // now fails (no payment method). A fixed +30d can land a day short of the renewal boundary.
        stripeService.advanceTestClock(createdClockId, renewalAdvanceTarget(cs));

        Event failed = waitForEvent(Set.of("invoice.payment_failed"), createdCustomerId, null, null);
        assertNotNull(failed, "invoice.payment_failed event not received from Stripe");
        log.info("IT[fail]: replaying invoice.payment_failed event id={}", failed.getId());
        stripeWebhookService.handleEvent(failed);

        UserSubscription after = subscriptionRepository.findByUserId(userId).orElseThrow();
        assertEquals("PAST_DUE", after.getStatus(), "subscription should be marked PAST_DUE on payment failure");
        log.info("IT[fail]: subscription marked PAST_DUE for userId={}", userId);
    }

    /** Upgrading BASIC -> PREMIUM mid-period takes effect immediately (prorated). */
    @Test
    void upgradeMidPeriod_takesEffectImmediately() throws Exception {
        Map<String, Object> basic = subscribeViaService("BASIC", "MONTHLY");
        assertEquals("BASIC", basic.get("planName"));
        log.info("IT[upgrade]: subscribed BASIC via service stripeSub={}", createdSubscriptionId);

        Map<String, Object> premium = subscriptionService.subscribeViaStripe(userId, "PREMIUM", "MONTHLY", null, true);
        assertEquals("PREMIUM", premium.get("planName"), "upgrade should switch plan to PREMIUM immediately");
        assertEquals("ACTIVE", premium.get("status"));
        log.info("IT[upgrade]: upgraded to PREMIUM via service");

        // Replay the customer.subscription.updated event Stripe fires for the prorated price change.
        Event updated = waitForEvent(Set.of("customer.subscription.updated"), createdCustomerId, null, null);
        assertNotNull(updated, "customer.subscription.updated event not received after upgrade");
        log.info("IT[upgrade]: replaying customer.subscription.updated event id={}", updated.getId());
        stripeWebhookService.handleEvent(updated);

        UserSubscription after = subscriptionRepository.findByUserId(userId).orElseThrow();
        assertEquals("PREMIUM", after.getPlanName(), "webhook projector should mirror PREMIUM plan");
        log.info("IT[upgrade]: webhook mirrored plan=PREMIUM for userId={}", userId);
    }

    /** Downgrading PREMIUM -> BASIC mid-period is deferred: plan stays PREMIUM with a pending BASIC change. */
    @Test
    void downgradeMidPeriod_deferred() throws Exception {
        subscribeViaService("PREMIUM", "MONTHLY");
        log.info("IT[downgrade]: subscribed PREMIUM via service stripeSub={}", createdSubscriptionId);
        // Replay the initial invoice.paid so the first payment is recorded.
        // Idempotent: a live backend processing the same webhook won't double-record (stripe_invoice_id).
        Event initialPaid = waitForEvent(INVOICE_PAID_TYPES, createdCustomerId, null, null);
        assertNotNull(initialPaid, "initial invoice.paid event not received after subscribe");
        stripeWebhookService.handleEvent(initialPaid);

        // A deferred downgrade (proration_behavior=none) must not create a new invoice/charge. Assert
        // via Stripe directly (source of truth) so a live backend writing to the shared DB can't race
        // the row count. The only invoice on the customer is the initial subscription_create invoice.
        int invoicesBefore = listInvoicesForCustomer(createdCustomerId).size();
        Map<String, Object> down = subscriptionService.subscribeViaStripe(userId, "BASIC", "MONTHLY", null, true);
        assertEquals("PREMIUM", down.get("planName"), "current plan should remain PREMIUM until period end");
        assertEquals("BASIC", down.get("pendingPlanName"), "pending plan should be BASIC");
        assertEquals("MONTHLY", down.get("pendingBillingCycle"));
        assertEquals("ACTIVE", down.get("status"));
        assertEquals(invoicesBefore, listInvoicesForCustomer(createdCustomerId).size(),
                "deferred downgrade must not create a new invoice");
        log.info("IT[downgrade]: downgrade deferred, plan=PREMIUM pending=BASIC for userId={}", userId);
    }

    /** Cancelling a paid subscription schedules a drop to FREE at period end (cancel_at_period_end). */
    @Test
    void cancelToFree_scheduledAtPeriodEnd() throws Exception {
        subscribeViaService("BASIC", "MONTHLY");
        log.info("IT[cancel]: subscribed BASIC via service stripeSub={}", createdSubscriptionId);

        subscriptionService.cancel(userId);

        UserSubscription afterCancel = subscriptionRepository.findByUserId(userId).orElseThrow();
        assertEquals("CANCELLED", afterCancel.getStatus());
        assertEquals("FREE", afterCancel.getPendingPlanName());
        assertNotNull(afterCancel.getEndDate());
        log.info("IT[cancel]: cancel scheduled, status=CANCELLED pending=FREE endDate={}", afterCancel.getEndDate());

        // Replay the subscription.updated event Stripe fires for cancel_at_period_end=true.
        Event updated = waitForEvent(Set.of("customer.subscription.updated"), createdCustomerId, null, null);
        assertNotNull(updated, "customer.subscription.updated event not received after cancel");
        log.info("IT[cancel]: replaying customer.subscription.updated event id={}", updated.getId());
        stripeWebhookService.handleEvent(updated);

        UserSubscription after = subscriptionRepository.findByUserId(userId).orElseThrow();
        assertEquals("CANCELLED", after.getStatus());
        assertEquals("FREE", after.getPendingPlanName());
        assertNotNull(after.getStripeSubscriptionId(), "stripeSubscriptionId remains until the period-end deletion event");
        log.info("IT[cancel]: webhook mirrored cancel for userId={}", userId);
    }

    // ===================== Helpers =====================

    private static long nowEpoch() {
        return System.currentTimeMillis() / 1000L;
    }

    /** Convert a Stripe epoch-second timestamp (e.g. an invoice's periodStart) to a LocalDateTime. */
    private static LocalDateTime ldtFromEpoch(Long epochSeconds) {
        return epochSeconds == null ? null
                : LocalDateTime.ofInstant(Instant.ofEpochSecond(epochSeconds), ZoneId.systemDefault());
    }

    /**
     * Absolute epoch to advance a test clock to so a single monthly renewal fires. A monthly
     * billing period is at most 31 days, so +32d always crosses exactly one renewal boundary
     * (and never two). A fixed +30d can land one day short of a calendar-month boundary
     * (e.g. Aug 29 + 30d = Sep 28, but the renewal is Sep 29) and miss the renewal entirely.
     * (stripe-java 32.x removed Subscription#getCurrentPeriodEnd, so a fixed margin is used.)
     */
    private long renewalAdvanceTarget(ClockSub cs) {
        return cs.frozenEpoch() + 32L * 86_400L;
    }

    /** List a customer's invoices directly from Stripe (source of truth), e.g. to assert a deferred
     *  downgrade (proration=none) created no new invoice — race-safe vs a live backend writing rows. */
    private List<Invoice> listInvoicesForCustomer(String customerId) throws StripeException {
        Map<String, Object> params = new HashMap<>();
        params.put("customer", customerId);
        params.put("limit", 100);
        return Invoice.list(params).getData();
    }

    /** Create a test clock + clock-owned customer + sandbox test-card (via test token) + subscription. */
    private ClockSub setupClockSubscription(String plan, String cycle, String testToken) throws StripeException {
        long t0 = nowEpoch();
        TestClock clock = stripeService.createTestClock(t0);
        createdClockId = clock.getId();
        UserSubscription sub = subscriptionService.getOrCreateSubscription(userId);
        stripeService.ensureCustomer(sub, clock.getId());
        createdCustomerId = sub.getStripeCustomerId();
        com.stripe.model.PaymentMethod pm = stripeService.createTestPaymentMethod(testToken);
        stripeService.attachDefaultPaymentMethod(sub, pm.getId());
        Subscription created = stripeService.createSubscription(sub, stripeService.priceIdFor(plan, cycle), clock.getId());
        createdSubscriptionId = created.getId();
        // Mirror the paid plan locally (the real subscribeViaStripe path does the same synchronously).
        sub.setPlanName(plan);
        sub.setBillingCycle(cycle);
        sub.setStatus("ACTIVE");
        sub.setPendingPlanName(null);
        sub.setPendingBillingCycle(null);
        subscriptionRepository.save(sub);
        return new ClockSub(t0, created);
    }

    /** Subscribe via the real service path (non-clock customer) using a sandbox success card (test token). */
    private Map<String, Object> subscribeViaService(String plan, String cycle) throws StripeException {
        com.stripe.model.PaymentMethod pm = stripeService.createTestPaymentMethod(SUCCESS_TOKEN);
        Map<String, Object> res = subscriptionService.subscribeViaStripe(userId, plan, cycle, pm.getId(), false);
        // Re-fetch the subscription row: subscribeViaStripe updates its own managed instance, so the
        // pre-call instance is stale (stripeCustomerId/stripeSubscriptionId would read back as null).
        UserSubscription sub = subscriptionRepository.findByUserId(userId).orElseThrow();
        createdCustomerId = sub.getStripeCustomerId();
        createdSubscriptionId = sub.getStripeSubscriptionId();
        return res;
    }

    /**
     * Poll Stripe's Event.list for an event of one of the given types whose object's customer matches,
     * skipping an already-seen event id and (for invoice events) any event for an already-handled
     * invoice id — Stripe emits both invoice.paid and invoice.payment_succeeded for a single invoice,
     * so excluding only the event id would match the sibling event of the first invoice instead of
     * waiting for the renewal invoice. Returns null after ~45s.
     */
    private Event waitForEvent(Set<String> types, String customerId, String excludeEventId,
                               String excludeInvoiceId) throws Exception {
        long deadline = System.currentTimeMillis() + 45_000L;
        while (System.currentTimeMillis() < deadline) {
            Map<String, Object> params = new HashMap<>();
            params.put("limit", 100);
            // Only look at events created since this test method started, so a busy sandbox account
            // (or a live backend processing the same events) cannot crowd the target out of the page.
            Map<String, Object> created = new HashMap<>();
            created.put("gte", testStartEpoch);
            params.put("created", created);
            EventCollection collection = Event.list(params);
            for (Event e : collection.getData()) {
                if (e.getType() == null || !types.contains(e.getType())) continue;
                if (excludeEventId != null && excludeEventId.equals(e.getId())) continue;
                StripeObject obj;
                try {
                    obj = e.getDataObjectDeserializer().deserializeUnsafe();
                } catch (Exception ex) {
                    continue;
                }
                String cust = null;
                if (obj instanceof Invoice inv) {
                    cust = inv.getCustomer();
                    if (excludeInvoiceId != null && excludeInvoiceId.equals(inv.getId())) continue;
                } else if (obj instanceof Subscription s) {
                    cust = s.getCustomer();
                }
                if (customerId != null && customerId.equals(cust)) return e;
            }
            Thread.sleep(2000L);
        }
        return null;
    }

    private record ClockSub(long frozenEpoch, Subscription subscription) {}
}
